# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orotangi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_modified',
            field=models.DateTimeField(),
        ),
    ]
